/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.*;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Scanner;

public class MyServer {
    public static void main(String[] args) {
        connectToServer();
    }


	// Method to connect to a server
    public static void connectToServer() {

        // Tries to connect to the server on port 4040. A successful connection will return a socket
        try(ServerSocket serverSocket = new ServerSocket(4040)) {
            Socket connectionSocket = serverSocket.accept();


            //Create Input&Outputstreams for the connection
            InputStream inputToServer = connectionSocket.getInputStream();	    // Creates inputstream taking input from connectionSocket. What we want to send to the server. 
            OutputStream outputFromServer = connectionSocket.getOutputStream();	// Creates outputstream getting output from connectionSocket. What we receives from the server. 

            Scanner scanner = new Scanner(inputToServer, "UTF-8");
            PrintWriter serverPrintOut = new PrintWriter(new OutputStreamWriter(outputFromServer, "UTF-8"), true);

            serverPrintOut.println("Hello World! Enter Peace to exit.");

            //Have the server take input from the client and echo it back
            //This should be placed in a loop that listens for a terminator text e.g. bye
            boolean done = false;

            while(!done && scanner.hasNextLine()) {
                String line = scanner.nextLine();
                serverPrintOut.println("Echo from <Your Name Here> Server: " + line);

                if(line.toLowerCase().trim().equals("peace")) {
                    done = true;
                }
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
